"""Builds public/insert-layouts.js from MIL-STD-1560C (w/Change 3) contact position tables.

Usage: python3 scripts/insert-layouts-1560.py MIL-STD-1560.pdf profiles.json > public/insert-layouts.js
Needs pdftotext (poppler). profiles.json maps catalog arrangement codes (e.g. "G35") to {size: count}.
Coordinates are true-position inches, front face of the pin insert, +x right, +y up (MIL-STD-1560 5.3e).
"""
import json, re, subprocess, sys

pdf, profiles_path = sys.argv[1], sys.argv[2]
text = subprocess.run(['pdftotext', '-layout', pdf, '-'], capture_output=True, text=True, check=True).stdout
heads = list(re.finditer(r'\(Insert arrangement (\d+)-(\d+)\)', text))
row = re.compile(r'(?<![\w.+-])([A-Za-z]{1,2}|\d{1,3})\s+([+-]?\s?\.\d{3})\s*\(\s*\d*\.\d+\s*\)\s+([+-]?\s?\.\d{3})\s*\(\s*\d*\.\d+\s*\)')
tables = {}
for i, m in enumerate(heads):
    seg = text[m.end():heads[i + 1].start() if i + 1 < len(heads) else len(text)]
    pts = tables.setdefault(f'{m.group(1)}-{m.group(2)}', {})
    for r in row.finditer(seg):
        cid, xy = r.group(1), [float(r.group(2).replace(' ', '')), float(r.group(3).replace(' ', ''))]
        if cid in pts and pts[cid] != xy and len(cid) == 1 and cid.isupper():
            cid = cid.lower()  # the PDF text layer renders some lowercase j as J
        pts.setdefault(cid, xy)

SHELL = {'A': 9, 'B': 11, 'C': 13, 'D': 15, 'E': 17, 'F': 19, 'G': 21, 'H': 23, 'J': 25}
# Mixed-size arrangements: contact position IDs of the larger size, from each figure's summary table.
MIXED = {
    'D15': ('16', 'P'), 'D97': ('16', 'C G L M'), 'E99': ('16', 'W Z'), 'F28': ('16', 'e Z'), 'F30': ('16', 'e'),
    'G39': ('16', 'r m'), 'J4': ('16', 'y z AA DD EE FF LL JJ'), 'J24': ('12', 'A B D E L M P R S T X Y'),
    'J43': ('16', 'a b c d e f g h k m n p q r s t u v w x'),
}
# Insert outline radius per shell size: farthest contact centre in any MIL-STD-1560 arrangement of that size, plus margin.
outline = {}
for key, pts in tables.items():
    shell = int(key.split('-')[0])
    if shell % 2 and pts:
        outline[shell] = max(outline.get(shell, 0), max((x * x + y * y) ** .5 for x, y in pts.values()))

profiles = json.load(open(profiles_path))
out = {}
for code, profile in profiles.items():
    shell = SHELL[code[0]]
    pts = tables.get(f'{shell}-{code[1:]}')
    total = sum(profile.values())
    if not pts or len(pts) != total:
        sys.exit(f'{code}: expected {total} positions, found {len(pts or {})}')
    sizes = list(profile)
    if len(sizes) == 1:
        size_of = lambda cid: sizes[0]
    else:
        big, ids = MIXED[code]
        ids = set(ids.split())
        other = next(s for s in sizes if s != big)
        if not ids <= set(pts) or len(ids) != profile[big]:
            sys.exit(f'{code}: size {big} ids {sorted(ids)} do not match the table')
        size_of = lambda cid, ids=ids, big=big, other=other: big if cid in ids else other
    out[code] = {'shell': shell, 'contacts': [[cid, x, y, size_of(cid)] for cid, (x, y) in pts.items()]}

print('// Generated by scripts/insert-layouts-1560.py from MIL-STD-1560C w/Change 3 (3 Feb 2021). Do not edit by hand.')
print('// Each contact: [position ID, x in, y in, contact size]. Front face of the pin insert, +x right, +y up; the socket insert is the mirror image.')
print("export const insertSource = {verification: 'verified', source: 'MIL-STD-1560C w/Change 3, Insert Arrangements for MIL-DTL-38999 (contact position tables, figures 1-9)', source_url: 'https://quicksearch.dla.mil/'};")
print('export const insertOutline = ' + json.dumps({k: round(v + 0.075, 3) for k, v in sorted(outline.items())}) + ';')
print('export const insertLayouts = {')
for code, v in out.items():
    print(f'  {code}: {json.dumps(v, separators=(",", ":"))},')
print('};')
